<?php
defined('BASEPATH') or exit('No direct script access allowed');
class Employeecommissions extends Admin_controller
{
    public function __construct()
    {
        parent::__construct();
        if(get_user_role()!='user'){
            redirect(site_url('admin/permission/denied/'));
        }
        $this->load->model('User_model');
	$this->load->model('Employeecommission_model');
    }
    
    /* List all employee mission slip */
    public function index()
    {
        if(!$GLOBALS['employeecommission_permission']['view'] && !$GLOBALS['employeecommission_permission']['view_own']){
            access_denied('employeecommission');
        }
		
	//******************** Initialise ********************/
        //Users
        $data['filter_user'] = $this->User_model->get('',"userid, CONCAT(name,' ',surname) as name"," userrole IN(3,6) "); //Salesman and POS
        $data['filter_user'] = dropdown($data['filter_user'],'userid',"name");        
        //******************** End Initialise ********************/
        
        $data['title'] = lang('page_employeecommissions');
        $this->load->view('admin/employeecommissions/manage', $data);
    }
    
    /* List all hardwares by ajax */
    public function ajax($filter_user='')
    {
        //Filter By User
        $params = array('filter_user'=>$filter_user);		
        $this->app->get_table_data('employeecommissions', $params);        
    }
    
    //Generate Comission Slip PDF by Cronjob
    public function generateslip($month_year = '')
    {
        //If Not Pass Param Month-Year It will set default 
        if($month_year==''){
            $month_year = date('Y-m',strtotime("-1 month"));
        }
        
        if(!$GLOBALS['employeecommission_permission']['create']){
            access_denied('employeecommission');
        }
        
        //Submit Page
        if ($this->input->post()) {            
            $response = $this->Employeecommission_model->create_employeecommissionslip($month_year);        
            if (is_numeric($response) && $response>0) {                    
               set_alert('success', sprintf(lang('cronjob_generated_successfully'),lang('page_employeecommission')));
               redirect(site_url('admin/employeecommissions/generateslip/'.$month_year));
            }
            else{
               set_alert('danger', $response);
            }
        }
        
        $data = '';        
        $this->load->view('admin/employeecommissions/generateslip', $data);
    }
    
    //Download Commission Slip Generated by Cronjob
    public function downloadslip($slipnr)
    {
        $data['slipnr'] = $slipnr;
        $file = $this->Employeecommission_model->downloadslip($data['slipnr']);                  
    }
}
